### ISSUE TITLE
Documentation Contribution

### ISSUE THREAD

**Issue by dralabeing** [armleo/OpenLane#6]
Feedback for https://armleo-openlane.readthedocs.io/en/latest/docs/source/contributing_to_docs.html#installation-of-sphinx-for-documentation

Consider one section 
Contributing to OpenLane
  Documentation Guide
  Developer's guide

Current sections are haphazardly organized. Same type of information is strewn in different sections. see below for specifics.
Guidelines should be up, front and center.  
Here's a suggested layout: (Please please organize what you plan to inform and how they will be situated logically)-> This is not a nice to have but a must and will only cause confusion when merging at the end. Users should directed logically to sections that are clearly , hierarchically titled to find the information not some kind of sphagetti flow. I cannot approve any doc changes that atleast reasonably comply with layout guidelines.

Guidelines
  Writing Style and Consistency
  Do's and Don'ts 

Organize content from Everything under (Keep trademarks...which is not a good way to title a heading)
  How to Contribute into this section (some writing sytle stuff is also here..move to Writing Style section), Header structure into suitable sub-headings under Guidelines These sections currently are all essentially guidelines and suggestions. 

Installing Sphinx
Adding your Contributions
  Making screenshots
...

Checking your changes
Troubleshooting

Keep titles consistent - If using progressive verbs (like Contributing..then keep that consistent.
TItle-> Contributing to OpenLane Documentation (Contributing to OpenLane Development etc)
Again- Writing style, Guidelines  ..Adhere strictly
In order to contribute to documentation, it is useful to take a look at a preview, before pushing your changes. For this purpose, you can install the sphinx and build the documentation. Should become
To contribute to documentation, check the following - something like (add a checklist)

- Check Guidelines (Point to Link)
- Preview your changes
- Seek a Review and Approval from Project member
- Commit change

Then you can view the generated html files using Firefox or other browser. Should be :
View the generated html files... (Don't use you can, just active voice...Check all your writing style to ensure this is followed and such feedback need not be repeated.

Instead of assuming directory position, explicitly state the directory to be  using cd etc. Don't encode assumptions into the script alone.
Reference link to sphinx is missing. Also reference to RST is missing.

Topics for Troubleshooting should be nicely organized. These are all randomly added now.. steps, checking installation (??),notes
List clearly the types of problems the user is likely to encounter while contributing to doc and code Not for installation. Very confusing currently.

**Comment by armleo** [comment]
> Current sections are haphazardly organized. Same type of information is strewn in different sections. see below for specifics.

Without examples its not clear what you mean.

> Guidelines should be up, front and center.

I am completely lost on the meaning of this sentence.

> Here's a suggested layout: (Please please organize what you plan to inform and how they will be situated logically)-> This is not a nice to have but a must and will only cause confusion when merging at the end. Users should directed logically to sections that are clearly , hierarchically titled to find the information not some kind of sphagetti flow. I cannot approve any doc changes that atleast reasonably comply with layout guidelines.

> Keep titles consistent - If using progressive verbs (like Contributing..then keep that consistent.

Need examples.

> Organize content from Everything under

Sorry, I have no idea what "everything under" means in this context.

> (Keep trademarks...which is not a good way to title a heading)
Renamed and restructured. Is it better?

> In order to contribute to documentation, it is useful to take a look at a preview, before pushing your changes. For this purpose, you can install the sphinx and build the documentation. Should become
To contribute to documentation, check the following - something like (add a checklist)
Check Guidelines (Point to Link)
Preview your changes
Seek a Review and Approval from Project member
Commit change

Done.

> Then you can view the generated html files using Firefox or other browser. Should be :
View the generated html files... (Don't use you can, just active voice...Check all your writing style to ensure this is followed and such feedback need not be repeated.

Done.

> Instead of assuming directory position, explicitly state the directory to be using cd etc. Don't encode assumptions into the script alone.
Reference link to sphinx is missing. Also reference to RST is missing.

I made changes mentioning this. cd should be first command of the page, but other sections assume that each next code is running in the same terminal session as previous.

> Reference link to sphinx is missing. Also reference to RST is missing.

Done.

> Topics for Troubleshooting should be nicely organized. These are all randomly added now.. steps, checking installation (??),notes
List clearly the types of problems the user is likely to encounter while contributing to doc and code Not for installation. Very confusing currently.

I need examples. Currently they are organized in order of frequency.

**Comment by dralabeing** [comment]
@armleo I have provided detailed feedback - If something is not clear please reach out separately for a brief 1:1. It is difficult to cut and paste and respond to your counter questions.

Note, that without GH issues being properly understood and addressed, they will not be approved for commits, closure and will not count for project evaluations.
